### ISSUE TITLE
Webpack Server

### ISSUE THREAD

**Issue by ravishwetha** [arishuynhvan/SPi-Reader#16]
![screen shot 2016-09-02 at 2 57 25 pm](https://cloud.githubusercontent.com/assets/18163420/18195378/a97e6966-711d-11e6-83e7-c3b10cc4514f.png)

Hey do you instructions to set this up?

**Comment by arishuynhvan** [comment]
Please try to pull the master again and double check the file paths in webpack.config.js (right now it's compatible for win so you may want to change it to Mac compatible if the error persists)
